services:
  playground-api:
    image: {{ region }}-docker.pkg.dev/{{ project_id }}/playground/playground-api:latest
    container_name: playground-api
    restart: always
    privileged: true
    ports:
      - "80:2000"
    environment:
      COMPILE_CPU_TIME: 10000 # 10 seconds
      COMPILE_MEMORY_LIMIT: 300000000 # 300 MB
      COMPILE_TIMEOUT: 20000 # 20 seconds
      DISABLE_NETWORKING: "false"
      LOG_LEVEL: INFO
      MAX_CONCURRENT_JOBS: 100
      MAX_OPEN_FILES: 200
      OUTPUT_MAX_SIZE: 10240  # 10 KB
      PUBLIC_KEY: ca7fd8408500327b40d4da02dbc34881b2a379ccd3913a9d06e810a8fdb66329
      RUN_CPU_TIME: 30000 # 30 seconds
      RUN_MEMORY_LIMIT: 500000000  # 500 MB
      RUN_TIMEOUT: 45000 # 45 seconds
      MAX_FILE_SIZE: 20000000 # 20 MB
    tmpfs:
      - /tmp:exec


