replicaCount: 1

image:
  repository: haproxy
  tag: "2.9"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: "34.63.99.40"

backend:
  serviceName: ai-assistant
  servicePort: 3001
  healthPath: /api/playground/assistant/health

resources: {}

ssl:
  ca:
  crt:
  key:
  port: 8443
  certificate: "dev-playground-assistant.kabila.app.pem"
