http:
  routers:
    playground:
      rule: "Host(`{{ playground.domain }}`) && PathPrefix(`/api/playground`)"
      service: playground-service
      middlewares:
        - cors-headers
        - playground-ratelimit
        # - required-auth
      tls:
        certResolver: myresolver

  services:
    playground-service:
      loadBalancer:
        servers:
          - url: "http://{{ playground.host }}:{{ playground.port }}"

  middlewares:
    playground-ratelimit:
      rateLimit:
        average: 60
        period: 1m
    cors-headers:
      headers:
        accessControlAllowOriginList: 
          - "*"
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowCredentials: true
    # required-auth:
    #   plugin:
    #     validate-headers:
    #       headers:
    #         - name: "Authorization"
    #           required: true
    #           matchtype: one
    #           values:
    #             - "^Bearer .*"
    #           regex: true