http:
  routers:
    playground-execution:
      rule: "Host(`{{ playground.domain }}`) && PathPrefix(`/api/playground/execute`)"
      service: playground-service
      middlewares:
        - cors-headers
        - playground-execution-ratelimit
      tls:
        certResolver: myresolver
    playground:
      rule: "Host(`{{ playground.domain }}`) && PathPrefix(`/api/playground`)"
      service: playground-service
      middlewares:
        - cors-headers
        - playground-ratelimit
      tls:
        certResolver: myresolver

  services:
    playground-service:
      loadBalancer:
        servers:
          - url: "http://{{ playground.host }}:{{ playground.port }}"

  middlewares:
    playground-execution-ratelimit:
      rateLimit:
        burst: 1
        average: 15
        period: 1m
    playground-ratelimit:
      rateLimit:
        burst: 3
        average: 60
        period: 1m
    cors-headers:
      headers:
        accessControlAllowOriginList: 
          - "https://dev.portal.hedera.com"
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
          - DELETE
        accessControlAllowHeaders:
          - Content-Type
          - Authorization
        accessControlAllowCredentials: true