replicaCount: 1

image:
  repository: us-west1-docker.pkg.dev/playground-production-441511/playground/spoe-auth
  tag: "0.1.0@sha256:05e35b7408e3efad6db26d1725542635b21443728356b8bdde9cfa3851c9729a"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

# Environment variables for SPOE authentication
env:
  # PASETO configuration
  pasetoV4PublicKeyHex: "ca7fd8408500327b40d4da02dbc34881b2a379ccd3913a9d06e810a8fdb66329"  # Required: Ed25519 public key in HEX format
  ignoreExp: "true"         # Optional: ignore token expiration
  requireAud: ""            # Optional: expected audience
  requireIss: ""            # Optional: expected issuer
  userField: "userId"       # Optional: claim to extract user id (default: userId, fallback to sub)
  
  # Admin bypass
  adminApiKey: ""           # Optional: bypass when X-API-Key matches
  
  # SPOE configuration
  authArg: "auth"           # Optional: SPOE arg name with token (default: auth)
  apiKeyArg: "api_key"      # Optional: SPOE arg name with api key (default: api_key)
  messageName: "verify"     # Optional: SPOE message name (default: verify)
  
  # Service configuration
  mode: "spoe"              # Mode: spoe or http

  debug: "true"              # Debug mode: true or false

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

healthCheck:
  enable: true
  type: TCP      
  port: spoe         
  readiness:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 15
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 2
  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 3
  startup:
    enabled: false    
    periodSeconds: 5
    failureThreshold: 30
    timeoutSeconds: 2