name: Deploy Playground Application

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: 'Deployment - (instance group)'
        required: true
        default: 'poc'
jobs:
  update-vms:
    environment: ${{ 
      github.ref == 'refs/heads/master' && 'production' || 
      'develop' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout playground repository
      uses: actions/checkout@v4
      with:
        repository: 'hedera-dev/playground-backend'  
        ref: ${{ github.ref }}
        path: playground-backend

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ vars.GCP_PLAYGROUND_WORKLOAD_IDP }}
        service_account: ${{ vars.GCP_PLAYGROUND_SERVICE_ACCOUNT }}

    - name: Upload docker-compose file to GCS bucket
      run: |
        gcloud storage cp ./playground-backend/infrastructure/terraform/gcloud/app/templates/playground/docker-compose.yaml gs://${{vars.PLAYGROUND_BUCKET_NAME}}/playground/docker-compose.yaml